# Generated by Django 4.1.1 on 2022-09-30 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.TextField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology Engineering', 'Information Technology Engineering'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Electronics Engineering', 'Electronics Engineering')], max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('bith_certificate', models.ImageField(null=True, upload_to='')),
                ('leaving_certificate', models.ImageField(null=True, upload_to='')),
                ('Application_Status', models.TextField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('message', models.TextField(default='', max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
