# Generated by Django 4.1.1 on 2022-09-30 02:27

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0002_profile_disability_profile_firstname_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
